name: build and package openvds

on:
  push:
  workflow_dispatch:

jobs:
  package-openvds:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: build open vds
        run: |
          cd ThirdParty
          cd openvds
          mkdir build
          cd build
          cmake ..
          make OpenVDS -j2
          dir

  package-openvds-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: build open vds
        run: |
          cd ThirdParty
          cd openvds
          mkdir build
          cd build
          cmake ..
          make OpenVDS -j2
          ls 
